### ISSUE TITLE
Hey, dynamodb-marshaler aliases.

### ISSUE THREAD

**Issue by nackjicholson** [doostin/dynamaestro#1]
I checked out how you were manually aliasing the dynamodb-marshaler methods in this project and just wanted to let you know that I added optional aliases to the project as part of version 1.1.0.

`marhsalItem` can be used with `.toDDB`

`unmarshalItem` can be used with `.toJS`

``` javascript
var marshaler = require('dynamodb-marshaler');

marshaler.toDDB({foo: 'bar'});
marshaler.toJS({foo: {S: 'bar'}});
```

You can also just require them individually as an alternative:

``` javascript
var toJS = require('dynamodb-marshaler/marshalItem');
```

Hope that makes this easier for you.

**Comment by doostin** [comment]
Thanks, I'll take a crack at updating!
