### ISSUE TITLE
Support IAM Role usage and dynamo config options

### ISSUE THREAD

**Issue by wilsonwc** [doostin/dynamaestro#2]
Out of the box aws-sdk supports using IAM Roles for authentication if no accessKey & secret is set.  It would be nice to do something more like the vogels library where you could either pass in the existing dynamo object if you have it, or pass in an object that would configure all the possible aws/dynamo options (currently dynamo options like maxRetries are not accessable).  I will try to send a PR

**Comment by doostin** [comment]
Merged in your commit, thanks!
